### ISSUE TITLE
WebDAV: Error: Invalid response: 401

### ISSUE THREAD

**Issue by wjjessen** [subdavis/Tusk#360]
### Steps to reproduce - current behaviour

I have an issue with Tusk v2024.8.10. I had to reinstall Tusk and when I try to add a WebDAV server I get the following error:

"Error: Cannot request origin permission for https://<KeePass_folder_path> since it was not declared in the manifest".

### What is the expected behaviour

After clicking "Add Server", I expect to see a list of KeePass databases found by Tusk under the entered URL to select from.

#### Additional remarks

Previously, Tusk worked as expected. Existing setups with v2024.8.10 continue to work, they just can't discover the databases under the previously entered URL when clicking "Scan". When "Scan" is clicked for an existing setup with Tusk v2024.8.10, it shows "Error: Invalid response: 401".

#### Environment 

**Operating System:**

Manjaro Linux 6.9.12-3

**Browser vendor and version:**

LibreWolf v128.0.3-2

**Storage Provider:**

Storage: Nextcloud

**Comment by wjjessen** [comment]
Tusk was updated to v2024.8.20 in the FF Add-on store, so it automatically updated in LibreWolf. Now, when I try to "Add Server" it shows "Error: Invalid response: 401".

**Comment by subdavis** [comment]
The permission error is fixed.  I cannot reproduce the 401 error (without entering invalid credentials, of course).

Please provide more information about your webDAV configration, including the authentication mechanism (Digest? Basic?)

Does it work on regular Firefox?  Does it work on Chrome?

**Comment by tibacher** [comment]
Hi,

i have a almost the same behavior. I get 401 almost all time in my "main firefox" window but in a "private window" it works seamless! It only occours on my Windows 10 PC not on my MacBook. Reinstalling Tusk didn't fix it.
![grafik](https://github.com/user-attachments/assets/97ddfe60-fc7c-4695-bed2-5ad9e14c36f9)

WebDAV: Nextcloud (29.0.5) WebDAV
Firefox Version: 129.0.2 (64-Bit) (Windows)

**Comment by Horst12345** [comment]
Same here:
Normal Firefox Window (Version 129.0.2 -64-bit) error 401:
![grafik](https://github.com/user-attachments/assets/08c39541-4b2e-4f5b-b0de-4968888b93e2)

When i integrate the WebDav connection in private mode everything is working like a charm:
![grafik](https://github.com/user-attachments/assets/976e59c1-8b4f-407d-bbb3-a594f0abbdcf)


Problems started with current updates Tusk version. Beforce august update everything was working.

WebDav Sever = [Nextcloud Hub 8 (29.0.5)
Error Log from Nextcloud:
NotAuthenticated  - No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

**Comment by Horst12345** [comment]
Microsoft Edge - Version 128.0.2739.42 (64-bit) - Working

![grafik](https://github.com/user-attachments/assets/25be6441-e3de-4910-a819-cecfaf171ca6)

**Comment by subdavis** [comment]
> NotAuthenticated - No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

Thank you , that's helpful context.

**Comment by subdavis** [comment]
The latest version on firefox is `2024.8.20` which did have some fixes, but it seemed this thread was still having a problem after that.

**Comment by bigdestroyer** [comment]
Agreed, same error here. Have the Chrome extension added to Vivaldi browser installed. Work PC which has been set up prior to 2024.8.2 still works even though now on that version. Try to set it up on 2024.8.2 does not work

**Comment by ivanjx** [comment]
unlocking database also gives 404 error on normal window but works fine on private window

**Comment by steeb-k** [comment]
2024.8.20 - I was getting the 401 error message, but could successfully authenticate in a private window. Logging out of my Nextcloud instance allowed me to login using the app password through Tusk - and logged me back into my Nextcloud instance in the browser, as well. It appears that the issue is likely related to 2FA authentication, since I had to use an app password to get in, but the stored credentials when you have already logged in via normal password + 2FA stop Tusk from successfully authenticating with any method. 

So a workaround (if your Nextcloud instance uses 2FA) is to logout of your Nextcloud account and log back in using an app password. Tusk seems to be flummoxed by the 2FA implementation in an already-logged-in Nextcloud instance.
